const WITH_ERRORS = true;
const WITHOUT_ERRORS = false;

const IGNORE_ORDER = false;
const PRESERVE_ORDER = true;

const SLOW_ENABLED = true;
const SLOW_DISABLED = false;

module.exports = {WITH_ERRORS, WITHOUT_ERRORS, IGNORE_ORDER, PRESERVE_ORDER, SLOW_ENABLED, SLOW_DISABLED};